In [2]:
import numpy as np 
import pandas as pd

In [3]:
messy_cust=pd.read_csv("/workspaces/codespaces-blank/b28e3d46-7442-4db4-bdea-dd7a13022bd6_messycustomers50.csv")

In [4]:
messy_cust.head()

,customer_id,full_name,email,age,city,signup_date,account_balance,phone
0,101,ethan hopper,ETHAN.HOPPER@GMAIL.COM,39.0,Seattle,2023-04-05,$1779.50,792-858-9935
1,102,Eva Gonzalez,Eva.Gonzalez@invalid_domain,49.0,New York,2023-01-03,NaN,323-338-9279
2,103,Mason Smith,mason.smith@corp.net,150.0,Denver,2023-07-08,-279.00,703-384-1106
3,104,Michael Anderson,michael.anderson@company.io,NaN,Austin,2023-06-09,3047.00,NaN
4,105,Laura Edwards,laura.edwards@email.com,28.0,New York,2023-07-04,6381.00,(967) 452-5333

In [5]:
messy_cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      50 non-null     int64
 1   full_name        50 non-null     str
 2   email            50 non-null     str
 3   age              40 non-null     float64
 4   city             50 non-null     str
 5   signup_date      50 non-null     str
 6   account_balance  43 non-null     str
 7   phone            43 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 3.3 KB

In [38]:
messy_cust['full_name']=messy_cust['full_name'].str.strip().str.title()

In [7]:
messy_cust['email']=messy_cust['email'].str.lower()

In [8]:
messy_cust.age.describe()

count     40.000000
mean      54.175000
std       39.418782
min       24.000000
25%       29.000000
50%       44.000000
75%       56.250000
max      200.000000
Name: age, dtype: float64

In [9]:
q1=messy_cust["age"].quantile(0.25)
q3 = messy_cust["age"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print(lower_bound, upper_bound)

-11.875 97.125

In [10]:
messy_cust["age"] = [
    x if lower_bound <= x <= upper_bound else 54
    for x in messy_cust["age"]
]

In [11]:
messy_cust.loc[messy_cust['email'].str.contains('@invalid_domain', na=False),'email'] = 'not_available'

In [12]:
messy_cust

,customer_id,full_name,email,age,city,signup_date,account_balance,phone
0,101,ethan hopper,ethan.hopper@gmail.com,39.0,Seattle,2023-04-05,$1779.50,792-858-9935
1,102,Eva Gonzalez,not_available,49.0,New York,2023-01-03,NaN,323-338-9279
2,103,Mason Smith,mason.smith@corp.net,54.0,Denver,2023-07-08,-279.00,703-384-1106
3,104,Michael Anderson,michael.anderson@company.io,54.0,Austin,2023-06-09,3047.00,NaN
4,105,Laura Edwards,laura.edwards@email.com,28.0,New York,2023-07-04,6381.00,(967) 452-5333
5,106,Bob Parker,bob.parker@domain.org,56.0,Chicago,INVALID_DATE,1791.00,665.400.6925
6,107,Benjamin Jackson,benjamin.jackson@company.io,26.0,New York,2023-11-08,13165.00,396-181-4814
7,108,david walker,david.walker@email.com,51.0,Los Angeles,2023-03-12,$5920.50,314-786-5374
8,109,Henry Turner,not_available,63.0,Chicago,2023-10-21,NaN,275-646-5010
9,110,Ian King,ian.king@domain.org,54.0,Denver,2023-04-22,-216.00,963-886-1916
10,111,Michael Johnson,michael.johnson@email.com,54.0,Austin,2023-05-03,3956.00,NaN
11,112,Benjamin Campbell,benjamin.campbell@email.com,35.0,Seattle,2023-07-21,8017.00,(246) 371-3287
12,113,Nina Evans,nina.evans@corp.net,56.0,Boston,2025-12-31,7519.00,697.508.6930
13,114,Michael Castle,michael.castle@corp.net,53.0,Chicago,2023-01-28,2296.00,256-742-3621
14,115,harper young,harper.young@corp.net,26.0,Austin,2023-07-20,$7768.50,641-357-1188
15,116,Harper Parker,not_available,29.0,Denver,2023-05-25,NaN,756-448-2827
16,117,Rachel Young,rachel.young@yahoo.com,54.0,New York,2023-12-24,-184.00,612-880-3927
17,118,James Black,james.black@company.io,54.0,Boston,2023-11-17,10477.00,NaN
18,119,Kevin Taylor,kevin.taylor@email.com,32.0,boston,2023-09-01,10313.00,(431) 600-1319
19,120,Grace Lee,grace.lee@email.com,37.0,New York,04-18-2022,14885.00,680.180.2403
20,121,Jacob Lopez,jacob.lopez@gmail.com,56.0,San Francisco,2023-03-22,8287.00,662-269-5342
21,122,isabella nelson,isabella.nelson@domain.org,35.0,Denver,2023-12-23,$3395.50,830-419-7537
22,123,Alexander Perez,not_available,45.0,Miami,2023-09-15,NaN,223-353-4681
23,124,Charlie Rodriguez,charlie.rodriguez@gmail.com,54.0,Denver,2023-04-19,-162.00,107-172-1964
24,125,Michael White,michael.white@gmail.com,54.0,Los Angeles,2023-02-17,4399.00,NaN
25,126,Paul Roberts,paul.roberts@domain.org,35.0,boston,2023-03-24,14956.00,(684) 690-8744
26,127,Nina Wright,nina.wright@domain.org,34.0,Chicago,2023/05/12,11296.00,541.462.7939
27,128,Liam King,liam.king@company.io,25.0,Chicago,2023-01-13,12431.00,447-919-2790
28,129,nina jackson,nina.jackson@yahoo.com,56.0,Miami,2023-03-14,$3106.50,385-573-5092
29,130,Charlie Hernandez,not_available,57.0,Chicago,2023-01-21,NaN,653-956-1241
30,131,Eva Edwards,eva.edwards@yahoo.com,54.0,Austin,2023-08-16,-159.00,985-510-1960
31,132,Ian Walker,ian.walker@gmail.com,54.0,Austin,2023-05-26,13363.00,NaN
32,133,Olivia Martinez,olivia.martinez@domain.org,66.0,boston,2023-11-23,8473.00,(258) 294-5861
33,134,Laura Brown,laura.brown@corp.net,56.0,New York,Jan 15 2024,1436.00,151.698.8811
34,135,James Scott,james.scott@yahoo.com,25.0,Denver,2023-02-28,3544.00,170-709-2113
35,136,harper martin,harper.martin@domain.org,29.0,Atlanta,2023-04-19,$751.50,734-183-7868
36,137,Alexander Gonzalez,not_available,58.0,Denver,2023-06-09,NaN,309-785-6147
37,138,Nina Thompson,nina.thompson@domain.org,54.0,Boston,2023-08-11,-434.00,174-109-8508
38,139,Charlotte Baker,charlotte.baker@gmail.com,54.0,Chicago,2023-09-07,8788.00,NaN
39,140,Oscar Castle,oscar.castle@email.com,26.0,chicago,2023-06-10,3084.00,(548) 953-9900
40,141,Evelyn Robinson,evelyn.robinson@corp.net,63.0,Denver,2023/05/12,11442.00,936.667.5905
41,142,Alexander Black,alexander.black@yahoo.com,38.0,Chicago,2023-02-24,9564.00,259-378-5616
42,143,mason white,mason.white@company.io,43.0,Seattle,2023-11-21,$4425.50,617-600-5114
43,144,Alice Green,not_available,62.0,Austin,2023-05-02,NaN,103-441-3143
44,145,Ethan Thompson,ethan.thompson@yahoo.com,54.0,Denver,2023-12-14,-337.00,109-214-2232
45,146,Henry Taylor,henry.taylor@corp.net,54.0,New York,2023-06-19,9552.00,NaN
46,147,Hannah Young,hannah.young@yahoo.com,24.0,SAN FRANCISCO,2023-06-26,14601.00,(140) 466-4441
47,148,Harper Martin,harper.martin@company.io,28.0,Los Angeles,2025-12-31,14985.00,995.516.3532
48,149,Nina Anderson,nina.anderson@yahoo.com,48.0,New York,2023-03-24,5942.00,901-521-5065
49,150,paul anderson,paul.anderson@company.io,28.0,Austin,2023-01-28,$7811.50,327-304-8541

In [13]:
messy_cust['account_balance'].isnull().sum()

np.int64(7)

In [14]:
messy_cust.fillna({'account_balance':0}, inplace=True)

,customer_id,full_name,email,age,city,signup_date,account_balance,phone
0,101,ethan hopper,ethan.hopper@gmail.com,39.0,Seattle,2023-04-05,$1779.50,792-858-9935
1,102,Eva Gonzalez,not_available,49.0,New York,2023-01-03,0,323-338-9279
2,103,Mason Smith,mason.smith@corp.net,54.0,Denver,2023-07-08,-279.00,703-384-1106
3,104,Michael Anderson,michael.anderson@company.io,54.0,Austin,2023-06-09,3047.00,NaN
4,105,Laura Edwards,laura.edwards@email.com,28.0,New York,2023-07-04,6381.00,(967) 452-5333
5,106,Bob Parker,bob.parker@domain.org,56.0,Chicago,INVALID_DATE,1791.00,665.400.6925
6,107,Benjamin Jackson,benjamin.jackson@company.io,26.0,New York,2023-11-08,13165.00,396-181-4814
7,108,david walker,david.walker@email.com,51.0,Los Angeles,2023-03-12,$5920.50,314-786-5374
8,109,Henry Turner,not_available,63.0,Chicago,2023-10-21,0,275-646-5010
9,110,Ian King,ian.king@domain.org,54.0,Denver,2023-04-22,-216.00,963-886-1916
10,111,Michael Johnson,michael.johnson@email.com,54.0,Austin,2023-05-03,3956.00,NaN
11,112,Benjamin Campbell,benjamin.campbell@email.com,35.0,Seattle,2023-07-21,8017.00,(246) 371-3287
12,113,Nina Evans,nina.evans@corp.net,56.0,Boston,2025-12-31,7519.00,697.508.6930
13,114,Michael Castle,michael.castle@corp.net,53.0,Chicago,2023-01-28,2296.00,256-742-3621
14,115,harper young,harper.young@corp.net,26.0,Austin,2023-07-20,$7768.50,641-357-1188
15,116,Harper Parker,not_available,29.0,Denver,2023-05-25,0,756-448-2827
16,117,Rachel Young,rachel.young@yahoo.com,54.0,New York,2023-12-24,-184.00,612-880-3927
17,118,James Black,james.black@company.io,54.0,Boston,2023-11-17,10477.00,NaN
18,119,Kevin Taylor,kevin.taylor@email.com,32.0,boston,2023-09-01,10313.00,(431) 600-1319
19,120,Grace Lee,grace.lee@email.com,37.0,New York,04-18-2022,14885.00,680.180.2403
20,121,Jacob Lopez,jacob.lopez@gmail.com,56.0,San Francisco,2023-03-22,8287.00,662-269-5342
21,122,isabella nelson,isabella.nelson@domain.org,35.0,Denver,2023-12-23,$3395.50,830-419-7537
22,123,Alexander Perez,not_available,45.0,Miami,2023-09-15,0,223-353-4681
23,124,Charlie Rodriguez,charlie.rodriguez@gmail.com,54.0,Denver,2023-04-19,-162.00,107-172-1964
24,125,Michael White,michael.white@gmail.com,54.0,Los Angeles,2023-02-17,4399.00,NaN
25,126,Paul Roberts,paul.roberts@domain.org,35.0,boston,2023-03-24,14956.00,(684) 690-8744
26,127,Nina Wright,nina.wright@domain.org,34.0,Chicago,2023/05/12,11296.00,541.462.7939
27,128,Liam King,liam.king@company.io,25.0,Chicago,2023-01-13,12431.00,447-919-2790
28,129,nina jackson,nina.jackson@yahoo.com,56.0,Miami,2023-03-14,$3106.50,385-573-5092
29,130,Charlie Hernandez,not_available,57.0,Chicago,2023-01-21,0,653-956-1241
30,131,Eva Edwards,eva.edwards@yahoo.com,54.0,Austin,2023-08-16,-159.00,985-510-1960
31,132,Ian Walker,ian.walker@gmail.com,54.0,Austin,2023-05-26,13363.00,NaN
32,133,Olivia Martinez,olivia.martinez@domain.org,66.0,boston,2023-11-23,8473.00,(258) 294-5861
33,134,Laura Brown,laura.brown@corp.net,56.0,New York,Jan 15 2024,1436.00,151.698.8811
34,135,James Scott,james.scott@yahoo.com,25.0,Denver,2023-02-28,3544.00,170-709-2113
35,136,harper martin,harper.martin@domain.org,29.0,Atlanta,2023-04-19,$751.50,734-183-7868
36,137,Alexander Gonzalez,not_available,58.0,Denver,2023-06-09,0,309-785-6147
37,138,Nina Thompson,nina.thompson@domain.org,54.0,Boston,2023-08-11,-434.00,174-109-8508
38,139,Charlotte Baker,charlotte.baker@gmail.com,54.0,Chicago,2023-09-07,8788.00,NaN
39,140,Oscar Castle,oscar.castle@email.com,26.0,chicago,2023-06-10,3084.00,(548) 953-9900
40,141,Evelyn Robinson,evelyn.robinson@corp.net,63.0,Denver,2023/05/12,11442.00,936.667.5905
41,142,Alexander Black,alexander.black@yahoo.com,38.0,Chicago,2023-02-24,9564.00,259-378-5616
42,143,mason white,mason.white@company.io,43.0,Seattle,2023-11-21,$4425.50,617-600-5114
43,144,Alice Green,not_available,62.0,Austin,2023-05-02,0,103-441-3143
44,145,Ethan Thompson,ethan.thompson@yahoo.com,54.0,Denver,2023-12-14,-337.00,109-214-2232
45,146,Henry Taylor,henry.taylor@corp.net,54.0,New York,2023-06-19,9552.00,NaN
46,147,Hannah Young,hannah.young@yahoo.com,24.0,SAN FRANCISCO,2023-06-26,14601.00,(140) 466-4441
47,148,Harper Martin,harper.martin@company.io,28.0,Los Angeles,2025-12-31,14985.00,995.516.3532
48,149,Nina Anderson,nina.anderson@yahoo.com,48.0,New York,2023-03-24,5942.00,901-521-5065
49,150,paul anderson,paul.anderson@company.io,28.0,Austin,2023-01-28,$7811.50,327-304-8541

In [41]:
messy_cust.dtypes

customer_id          int64
full_name              str
email                  str
age                float64
city                   str
signup_date            str
account_balance    float64
phone                int64
dtype: object

In [17]:
messy_cust['account_balance'] = pd.to_numeric(
    messy_cust['account_balance']
      .astype(str)
      .str.replace(r'[\$,]', '', regex=True),
    errors='coerce'
)
messy_cust['account_balance'].dtype

dtype('float64')

In [ ]:
messy_cust.fillna({'phone':'0'},inplace=True)

,customer_id,full_name,email,age,city,signup_date,account_balance,phone
0,101,ethan hopper,ethan.hopper@gmail.com,39.0,Seattle,2023-04-05,1779.5,792-858-9935
1,102,Eva Gonzalez,not_available,49.0,New York,2023-01-03,0.0,323-338-9279
2,103,Mason Smith,mason.smith@corp.net,54.0,Denver,2023-07-08,-279.0,703-384-1106
3,104,Michael Anderson,michael.anderson@company.io,54.0,Austin,2023-06-09,3047.0,0
4,105,Laura Edwards,laura.edwards@email.com,28.0,New York,2023-07-04,6381.0,(967) 452-5333
5,106,Bob Parker,bob.parker@domain.org,56.0,Chicago,INVALID_DATE,1791.0,665.400.6925
6,107,Benjamin Jackson,benjamin.jackson@company.io,26.0,New York,2023-11-08,13165.0,396-181-4814
7,108,david walker,david.walker@email.com,51.0,Los Angeles,2023-03-12,5920.5,314-786-5374
8,109,Henry Turner,not_available,63.0,Chicago,2023-10-21,0.0,275-646-5010
9,110,Ian King,ian.king@domain.org,54.0,Denver,2023-04-22,-216.0,963-886-1916
10,111,Michael Johnson,michael.johnson@email.com,54.0,Austin,2023-05-03,3956.0,0
11,112,Benjamin Campbell,benjamin.campbell@email.com,35.0,Seattle,2023-07-21,8017.0,(246) 371-3287
12,113,Nina Evans,nina.evans@corp.net,56.0,Boston,2025-12-31,7519.0,697.508.6930
13,114,Michael Castle,michael.castle@corp.net,53.0,Chicago,2023-01-28,2296.0,256-742-3621
14,115,harper young,harper.young@corp.net,26.0,Austin,2023-07-20,7768.5,641-357-1188
15,116,Harper Parker,not_available,29.0,Denver,2023-05-25,0.0,756-448-2827
16,117,Rachel Young,rachel.young@yahoo.com,54.0,New York,2023-12-24,-184.0,612-880-3927
17,118,James Black,james.black@company.io,54.0,Boston,2023-11-17,10477.0,0
18,119,Kevin Taylor,kevin.taylor@email.com,32.0,boston,2023-09-01,10313.0,(431) 600-1319
19,120,Grace Lee,grace.lee@email.com,37.0,New York,04-18-2022,14885.0,680.180.2403
20,121,Jacob Lopez,jacob.lopez@gmail.com,56.0,San Francisco,2023-03-22,8287.0,662-269-5342
21,122,isabella nelson,isabella.nelson@domain.org,35.0,Denver,2023-12-23,3395.5,830-419-7537
22,123,Alexander Perez,not_available,45.0,Miami,2023-09-15,0.0,223-353-4681
23,124,Charlie Rodriguez,charlie.rodriguez@gmail.com,54.0,Denver,2023-04-19,-162.0,107-172-1964
24,125,Michael White,michael.white@gmail.com,54.0,Los Angeles,2023-02-17,4399.0,0
25,126,Paul Roberts,paul.roberts@domain.org,35.0,boston,2023-03-24,14956.0,(684) 690-8744
26,127,Nina Wright,nina.wright@domain.org,34.0,Chicago,2023/05/12,11296.0,541.462.7939
27,128,Liam King,liam.king@company.io,25.0,Chicago,2023-01-13,12431.0,447-919-2790
28,129,nina jackson,nina.jackson@yahoo.com,56.0,Miami,2023-03-14,3106.5,385-573-5092
29,130,Charlie Hernandez,not_available,57.0,Chicago,2023-01-21,0.0,653-956-1241
30,131,Eva Edwards,eva.edwards@yahoo.com,54.0,Austin,2023-08-16,-159.0,985-510-1960
31,132,Ian Walker,ian.walker@gmail.com,54.0,Austin,2023-05-26,13363.0,0
32,133,Olivia Martinez,olivia.martinez@domain.org,66.0,boston,2023-11-23,8473.0,(258) 294-5861
33,134,Laura Brown,laura.brown@corp.net,56.0,New York,Jan 15 2024,1436.0,151.698.8811
34,135,James Scott,james.scott@yahoo.com,25.0,Denver,2023-02-28,3544.0,170-709-2113
35,136,harper martin,harper.martin@domain.org,29.0,Atlanta,2023-04-19,751.5,734-183-7868
36,137,Alexander Gonzalez,not_available,58.0,Denver,2023-06-09,0.0,309-785-6147
37,138,Nina Thompson,nina.thompson@domain.org,54.0,Boston,2023-08-11,-434.0,174-109-8508
38,139,Charlotte Baker,charlotte.baker@gmail.com,54.0,Chicago,2023-09-07,8788.0,0
39,140,Oscar Castle,oscar.castle@email.com,26.0,chicago,2023-06-10,3084.0,(548) 953-9900
40,141,Evelyn Robinson,evelyn.robinson@corp.net,63.0,Denver,2023/05/12,11442.0,936.667.5905
41,142,Alexander Black,alexander.black@yahoo.com,38.0,Chicago,2023-02-24,9564.0,259-378-5616
42,143,mason white,mason.white@company.io,43.0,Seattle,2023-11-21,4425.5,617-600-5114
43,144,Alice Green,not_available,62.0,Austin,2023-05-02,0.0,103-441-3143
44,145,Ethan Thompson,ethan.thompson@yahoo.com,54.0,Denver,2023-12-14,-337.0,109-214-2232
45,146,Henry Taylor,henry.taylor@corp.net,54.0,New York,2023-06-19,9552.0,0
46,147,Hannah Young,hannah.young@yahoo.com,24.0,SAN FRANCISCO,2023-06-26,14601.0,(140) 466-4441
47,148,Harper Martin,harper.martin@company.io,28.0,Los Angeles,2025-12-31,14985.0,995.516.3532
48,149,Nina Anderson,nina.anderson@yahoo.com,48.0,New York,2023-03-24,5942.0,901-521-5065
49,150,paul anderson,paul.anderson@company.io,28.0,Austin,2023-01-28,7811.5,327-304-8541

In [29]:
def transform_phone(phone_number:str):
    phone_number=phone_number.replace('(','')
    phone_number=phone_number.replace(')','')
    phone_number=phone_number.replace('-','')
    phone_number=phone_number.replace(' ','')
    phone_number=phone_number.replace('.','')
    phone_number=phone_number.strip()
    return int(phone_number)

In [30]:
messy_cust['phone'] = messy_cust['phone'].apply(transform_phone)

In [39]:
messy_cust

,customer_id,full_name,email,age,city,signup_date,account_balance,phone
0,101,Ethan Hopper,ethan.hopper@gmail.com,39.0,Seattle,2023-04-05,1779.5,7928589935
1,102,Eva Gonzalez,not_available,49.0,New York,2023-01-03,0.0,3233389279
2,103,Mason Smith,mason.smith@corp.net,54.0,Denver,2023-07-08,-279.0,7033841106
3,104,Michael Anderson,michael.anderson@company.io,54.0,Austin,2023-06-09,3047.0,0
4,105,Laura Edwards,laura.edwards@email.com,28.0,New York,2023-07-04,6381.0,9674525333
5,106,Bob Parker,bob.parker@domain.org,56.0,Chicago,INVALID_DATE,1791.0,6654006925
6,107,Benjamin Jackson,benjamin.jackson@company.io,26.0,New York,2023-11-08,13165.0,3961814814
7,108,David Walker,david.walker@email.com,51.0,Los Angeles,2023-03-12,5920.5,3147865374
8,109,Henry Turner,not_available,63.0,Chicago,2023-10-21,0.0,2756465010
9,110,Ian King,ian.king@domain.org,54.0,Denver,2023-04-22,-216.0,9638861916
10,111,Michael Johnson,michael.johnson@email.com,54.0,Austin,2023-05-03,3956.0,0
11,112,Benjamin Campbell,benjamin.campbell@email.com,35.0,Seattle,2023-07-21,8017.0,2463713287
12,113,Nina Evans,nina.evans@corp.net,56.0,Boston,2025-12-31,7519.0,6975086930
13,114,Michael Castle,michael.castle@corp.net,53.0,Chicago,2023-01-28,2296.0,2567423621
14,115,Harper Young,harper.young@corp.net,26.0,Austin,2023-07-20,7768.5,6413571188
15,116,Harper Parker,not_available,29.0,Denver,2023-05-25,0.0,7564482827
16,117,Rachel Young,rachel.young@yahoo.com,54.0,New York,2023-12-24,-184.0,6128803927
17,118,James Black,james.black@company.io,54.0,Boston,2023-11-17,10477.0,0
18,119,Kevin Taylor,kevin.taylor@email.com,32.0,Boston,2023-09-01,10313.0,4316001319
19,120,Grace Lee,grace.lee@email.com,37.0,New York,04-18-2022,14885.0,6801802403
20,121,Jacob Lopez,jacob.lopez@gmail.com,56.0,San Francisco,2023-03-22,8287.0,6622695342
21,122,Isabella Nelson,isabella.nelson@domain.org,35.0,Denver,2023-12-23,3395.5,8304197537
22,123,Alexander Perez,not_available,45.0,Miami,2023-09-15,0.0,2233534681
23,124,Charlie Rodriguez,charlie.rodriguez@gmail.com,54.0,Denver,2023-04-19,-162.0,1071721964
24,125,Michael White,michael.white@gmail.com,54.0,Los Angeles,2023-02-17,4399.0,0
25,126,Paul Roberts,paul.roberts@domain.org,35.0,Boston,2023-03-24,14956.0,6846908744
26,127,Nina Wright,nina.wright@domain.org,34.0,Chicago,2023/05/12,11296.0,5414627939
27,128,Liam King,liam.king@company.io,25.0,Chicago,2023-01-13,12431.0,4479192790
28,129,Nina Jackson,nina.jackson@yahoo.com,56.0,Miami,2023-03-14,3106.5,3855735092
29,130,Charlie Hernandez,not_available,57.0,Chicago,2023-01-21,0.0,6539561241
30,131,Eva Edwards,eva.edwards@yahoo.com,54.0,Austin,2023-08-16,-159.0,9855101960
31,132,Ian Walker,ian.walker@gmail.com,54.0,Austin,2023-05-26,13363.0,0
32,133,Olivia Martinez,olivia.martinez@domain.org,66.0,Boston,2023-11-23,8473.0,2582945861
33,134,Laura Brown,laura.brown@corp.net,56.0,New York,Jan 15 2024,1436.0,1516988811
34,135,James Scott,james.scott@yahoo.com,25.0,Denver,2023-02-28,3544.0,1707092113
35,136,Harper Martin,harper.martin@domain.org,29.0,Atlanta,2023-04-19,751.5,7341837868
36,137,Alexander Gonzalez,not_available,58.0,Denver,2023-06-09,0.0,3097856147
37,138,Nina Thompson,nina.thompson@domain.org,54.0,Boston,2023-08-11,-434.0,1741098508
38,139,Charlotte Baker,charlotte.baker@gmail.com,54.0,Chicago,2023-09-07,8788.0,0
39,140,Oscar Castle,oscar.castle@email.com,26.0,Chicago,2023-06-10,3084.0,5489539900
40,141,Evelyn Robinson,evelyn.robinson@corp.net,63.0,Denver,2023/05/12,11442.0,9366675905
41,142,Alexander Black,alexander.black@yahoo.com,38.0,Chicago,2023-02-24,9564.0,2593785616
42,143,Mason White,mason.white@company.io,43.0,Seattle,2023-11-21,4425.5,6176005114
43,144,Alice Green,not_available,62.0,Austin,2023-05-02,0.0,1034413143
44,145,Ethan Thompson,ethan.thompson@yahoo.com,54.0,Denver,2023-12-14,-337.0,1092142232
45,146,Henry Taylor,henry.taylor@corp.net,54.0,New York,2023-06-19,9552.0,0
46,147,Hannah Young,hannah.young@yahoo.com,24.0,San Francisco,2023-06-26,14601.0,1404664441
47,148,Harper Martin,harper.martin@company.io,28.0,Los Angeles,2025-12-31,14985.0,9955163532
48,149,Nina Anderson,nina.anderson@yahoo.com,48.0,New York,2023-03-24,5942.0,9015215065
49,150,Paul Anderson,paul.anderson@company.io,28.0,Austin,2023-01-28,7811.5,3273048541

In [36]:
messy_cust['city']=messy_cust['city'].str.strip().str.title()

In [37]:
messy_cust['city'].value_counts()

city
Denver           9
Chicago          9
New York         8
Austin           7
Boston           6
Seattle          3
Los Angeles      3
San Francisco    2
Miami            2
Atlanta          1
Name: count, dtype: int64

In [47]:
messy_cust['signup_date'].value_counts()

signup_date
2023-06-09    2
2025-12-31    2
2023-01-28    2
2023-04-19    2
2023-03-24    2
2023-05-12    2
2023-04-05    1
2023-01-03    1
2023-07-08    1
2023-07-04    1
2023-11-08    1
2023-03-12    1
2023-10-21    1
2023-04-22    1
2023-05-03    1
2023-07-21    1
2023-07-20    1
2023-05-25    1
2023-12-24    1
2023-11-17    1
2023-09-01    1
2022-04-18    1
2023-03-22    1
2023-12-23    1
2023-09-15    1
2023-02-17    1
2023-01-13    1
2023-03-14    1
2023-01-21    1
2023-08-16    1
2023-05-26    1
2023-11-23    1
2024-01-15    1
2023-02-28    1
2023-08-11    1
2023-09-07    1
2023-06-10    1
2023-02-24    1
2023-11-21    1
2023-05-02    1
2023-12-14    1
2023-06-19    1
2023-06-26    1
Name: count, dtype: int64

In [46]:
messy_cust['signup_date']=pd.to_datetime(messy_cust['signup_date'], errors='coerce', dayfirst=False,format='mixed')

In [52]:
messy_cust.fillna({'signup_date':pd.Timestamp('2020-01-01')}, inplace=True)

,customer_id,full_name,email,age,city,signup_date,account_balance,phone
0,101,Ethan Hopper,ethan.hopper@gmail.com,39.0,Seattle,2023-04-05,1779.5,7928589935
1,102,Eva Gonzalez,not_available,49.0,New York,2023-01-03,0.0,3233389279
2,103,Mason Smith,mason.smith@corp.net,54.0,Denver,2023-07-08,-279.0,7033841106
3,104,Michael Anderson,michael.anderson@company.io,54.0,Austin,2023-06-09,3047.0,0
4,105,Laura Edwards,laura.edwards@email.com,28.0,New York,2023-07-04,6381.0,9674525333
5,106,Bob Parker,bob.parker@domain.org,56.0,Chicago,2020-01-01,1791.0,6654006925
6,107,Benjamin Jackson,benjamin.jackson@company.io,26.0,New York,2023-11-08,13165.0,3961814814
7,108,David Walker,david.walker@email.com,51.0,Los Angeles,2023-03-12,5920.5,3147865374
8,109,Henry Turner,not_available,63.0,Chicago,2023-10-21,0.0,2756465010
9,110,Ian King,ian.king@domain.org,54.0,Denver,2023-04-22,-216.0,9638861916
10,111,Michael Johnson,michael.johnson@email.com,54.0,Austin,2023-05-03,3956.0,0
11,112,Benjamin Campbell,benjamin.campbell@email.com,35.0,Seattle,2023-07-21,8017.0,2463713287
12,113,Nina Evans,nina.evans@corp.net,56.0,Boston,2025-12-31,7519.0,6975086930
13,114,Michael Castle,michael.castle@corp.net,53.0,Chicago,2023-01-28,2296.0,2567423621
14,115,Harper Young,harper.young@corp.net,26.0,Austin,2023-07-20,7768.5,6413571188
15,116,Harper Parker,not_available,29.0,Denver,2023-05-25,0.0,7564482827
16,117,Rachel Young,rachel.young@yahoo.com,54.0,New York,2023-12-24,-184.0,6128803927
17,118,James Black,james.black@company.io,54.0,Boston,2023-11-17,10477.0,0
18,119,Kevin Taylor,kevin.taylor@email.com,32.0,Boston,2023-09-01,10313.0,4316001319
19,120,Grace Lee,grace.lee@email.com,37.0,New York,2022-04-18,14885.0,6801802403
20,121,Jacob Lopez,jacob.lopez@gmail.com,56.0,San Francisco,2023-03-22,8287.0,6622695342
21,122,Isabella Nelson,isabella.nelson@domain.org,35.0,Denver,2023-12-23,3395.5,8304197537
22,123,Alexander Perez,not_available,45.0,Miami,2023-09-15,0.0,2233534681
23,124,Charlie Rodriguez,charlie.rodriguez@gmail.com,54.0,Denver,2023-04-19,-162.0,1071721964
24,125,Michael White,michael.white@gmail.com,54.0,Los Angeles,2023-02-17,4399.0,0
25,126,Paul Roberts,paul.roberts@domain.org,35.0,Boston,2023-03-24,14956.0,6846908744
26,127,Nina Wright,nina.wright@domain.org,34.0,Chicago,2023-05-12,11296.0,5414627939
27,128,Liam King,liam.king@company.io,25.0,Chicago,2023-01-13,12431.0,4479192790
28,129,Nina Jackson,nina.jackson@yahoo.com,56.0,Miami,2023-03-14,3106.5,3855735092
29,130,Charlie Hernandez,not_available,57.0,Chicago,2023-01-21,0.0,6539561241
30,131,Eva Edwards,eva.edwards@yahoo.com,54.0,Austin,2023-08-16,-159.0,9855101960
31,132,Ian Walker,ian.walker@gmail.com,54.0,Austin,2023-05-26,13363.0,0
32,133,Olivia Martinez,olivia.martinez@domain.org,66.0,Boston,2023-11-23,8473.0,2582945861
33,134,Laura Brown,laura.brown@corp.net,56.0,New York,2024-01-15,1436.0,1516988811
34,135,James Scott,james.scott@yahoo.com,25.0,Denver,2023-02-28,3544.0,1707092113
35,136,Harper Martin,harper.martin@domain.org,29.0,Atlanta,2023-04-19,751.5,7341837868
36,137,Alexander Gonzalez,not_available,58.0,Denver,2023-06-09,0.0,3097856147
37,138,Nina Thompson,nina.thompson@domain.org,54.0,Boston,2023-08-11,-434.0,1741098508
38,139,Charlotte Baker,charlotte.baker@gmail.com,54.0,Chicago,2023-09-07,8788.0,0
39,140,Oscar Castle,oscar.castle@email.com,26.0,Chicago,2023-06-10,3084.0,5489539900
40,141,Evelyn Robinson,evelyn.robinson@corp.net,63.0,Denver,2023-05-12,11442.0,9366675905
41,142,Alexander Black,alexander.black@yahoo.com,38.0,Chicago,2023-02-24,9564.0,2593785616
42,143,Mason White,mason.white@company.io,43.0,Seattle,2023-11-21,4425.5,6176005114
43,144,Alice Green,not_available,62.0,Austin,2023-05-02,0.0,1034413143
44,145,Ethan Thompson,ethan.thompson@yahoo.com,54.0,Denver,2023-12-14,-337.0,1092142232
45,146,Henry Taylor,henry.taylor@corp.net,54.0,New York,2023-06-19,9552.0,0
46,147,Hannah Young,hannah.young@yahoo.com,24.0,San Francisco,2023-06-26,14601.0,1404664441
47,148,Harper Martin,harper.martin@company.io,28.0,Los Angeles,2025-12-31,14985.0,9955163532
48,149,Nina Anderson,nina.anderson@yahoo.com,48.0,New York,2023-03-24,5942.0,9015215065
49,150,Paul Anderson,paul.anderson@company.io,28.0,Austin,2023-01-28,7811.5,3273048541

In [53]:
messy_cust.to_csv("cleaned_cust.csv", index=False, encoding="utf-8")